### ISSUE TITLE
Create new Solution where the basis of your buils is test-driven development

### ISSUE THREAD

**Issue by Jvanderholst** [Jvanderholst/RandomizerFramework#1]
So this solution will be build using test-driven development. So please create a solution, a randomizer project and also the basis for test-driven development (unit tests, mocks). Adhere to the following guidelines: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions + https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines

**Comment by buzzfrog** [comment]
I have done a pull request on that. #3
